name: Extension Tests

on:
  push:
    branches: [ main, develop ]
    paths: ['extension/**']
  pull_request:
    branches: [ main ]
    paths: ['extension/**']

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        browser: [firefox, chromium]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: extension/pnpm-lock.yaml
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      working-directory: ./extension
      run: |
        pnpm install --frozen-lockfile
        pnpm exec playwright install --with-deps ${{ matrix.browser }}
    
    - name: Lint extension
      working-directory: ./extension
      run: pnpm run lint
      continue-on-error: true
    
    - name: Run tests
      working-directory: ./extension
      run: pnpm test -- --project=${{ matrix.browser }}
      env:
        CI: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.node-version }}
        path: |
          extension/test-results/
          extension/playwright-report/
        retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        cache-dependency-path: extension/pnpm-lock.yaml
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      working-directory: ./extension
      run: pnpm install --frozen-lockfile
    
    - name: Build extension
      working-directory: ./extension
      run: pnpm run build
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: extension/web-ext-artifacts/
        retention-days: 90